/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : AppointmentId,
  'startTime' : bigint,
  'status' : AppointmentStatus,
  'clientId' : ClientId,
  'staffId' : [] | [StaffId],
  'endTime' : bigint,
  'serviceId' : ServiceId,
}
export type AppointmentId = string;
export type AppointmentStatus = { 'scheduled' : null } |
  { 'noShow' : null } |
  { 'canceled' : null } |
  { 'completed' : null };
export interface Availability {
  'startTime' : bigint,
  'endTime' : bigint,
  'dayOfWeek' : bigint,
}
export interface BusinessProfile { 'name' : string, 'timeZone' : string }
export interface Client {
  'id' : ClientId,
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type ClientId = string;
export interface Price { 'currency' : string, 'amount' : bigint }
export interface PublicBookingRequest {
  'startTime' : bigint,
  'name' : string,
  'email' : [] | [string],
  'serviceId' : ServiceId,
  'phone' : [] | [string],
}
export interface Service {
  'id' : ServiceId,
  'name' : string,
  'durationMinutes' : bigint,
  'price' : [] | [Price],
}
export type ServiceId = string;
export interface Staff { 'id' : StaffId, 'name' : string }
export type StaffId = string;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addClient' : ActorMethod<[string, Client], undefined>,
  'addService' : ActorMethod<[string, Service], undefined>,
  'addStaff' : ActorMethod<[string, Staff], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookPublic' : ActorMethod<[string, PublicBookingRequest], AppointmentId>,
  'createAppointment' : ActorMethod<[string, Appointment], undefined>,
  'createBusiness' : ActorMethod<[string, string, string], undefined>,
  'getAllAppointments' : ActorMethod<[string], Array<Appointment>>,
  'getAllClients' : ActorMethod<[string], Array<Client>>,
  'getAllServices' : ActorMethod<[string], Array<Service>>,
  'getAllStaff' : ActorMethod<[string], Array<Staff>>,
  'getAppointment' : ActorMethod<[string, AppointmentId], [] | [Appointment]>,
  'getAvailability' : ActorMethod<[string, StaffId], [] | [Availability]>,
  'getAvailableSlots' : ActorMethod<[string, ServiceId, bigint], Array<bigint>>,
  'getBusiness' : ActorMethod<[string], [] | [BusinessProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClient' : ActorMethod<[string, ClientId], [] | [Client]>,
  'getService' : ActorMethod<[string, ServiceId], [] | [Service]>,
  'getStaff' : ActorMethod<[string, StaffId], [] | [Staff]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAvailability' : ActorMethod<[string, StaffId, Availability], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];