/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ClientId = IDL.Text;
export const Client = IDL.Record({
  'id' : ClientId,
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const ServiceId = IDL.Text;
export const Price = IDL.Record({ 'currency' : IDL.Text, 'amount' : IDL.Nat });
export const Service = IDL.Record({
  'id' : ServiceId,
  'name' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'price' : IDL.Opt(Price),
});
export const StaffId = IDL.Text;
export const Staff = IDL.Record({ 'id' : StaffId, 'name' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PublicBookingRequest = IDL.Record({
  'startTime' : IDL.Int,
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'serviceId' : ServiceId,
  'phone' : IDL.Opt(IDL.Text),
});
export const AppointmentId = IDL.Text;
export const AppointmentStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'noShow' : IDL.Null,
  'canceled' : IDL.Null,
  'completed' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : AppointmentId,
  'startTime' : IDL.Int,
  'status' : AppointmentStatus,
  'clientId' : ClientId,
  'staffId' : IDL.Opt(StaffId),
  'endTime' : IDL.Int,
  'serviceId' : ServiceId,
});
export const Availability = IDL.Record({
  'startTime' : IDL.Nat,
  'endTime' : IDL.Nat,
  'dayOfWeek' : IDL.Nat,
});
export const BusinessProfile = IDL.Record({
  'name' : IDL.Text,
  'timeZone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClient' : IDL.Func([IDL.Text, Client], [], []),
  'addService' : IDL.Func([IDL.Text, Service], [], []),
  'addStaff' : IDL.Func([IDL.Text, Staff], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookPublic' : IDL.Func(
      [IDL.Text, PublicBookingRequest],
      [AppointmentId],
      [],
    ),
  'createAppointment' : IDL.Func([IDL.Text, Appointment], [], []),
  'createBusiness' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllAppointments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getAllClients' : IDL.Func([IDL.Text], [IDL.Vec(Client)], ['query']),
  'getAllServices' : IDL.Func([IDL.Text], [IDL.Vec(Service)], ['query']),
  'getAllStaff' : IDL.Func([IDL.Text], [IDL.Vec(Staff)], ['query']),
  'getAppointment' : IDL.Func(
      [IDL.Text, AppointmentId],
      [IDL.Opt(Appointment)],
      ['query'],
    ),
  'getAvailability' : IDL.Func(
      [IDL.Text, StaffId],
      [IDL.Opt(Availability)],
      ['query'],
    ),
  'getAvailableSlots' : IDL.Func(
      [IDL.Text, ServiceId, IDL.Int],
      [IDL.Vec(IDL.Int)],
      ['query'],
    ),
  'getBusiness' : IDL.Func([IDL.Text], [IDL.Opt(BusinessProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClient' : IDL.Func([IDL.Text, ClientId], [IDL.Opt(Client)], ['query']),
  'getService' : IDL.Func([IDL.Text, ServiceId], [IDL.Opt(Service)], ['query']),
  'getStaff' : IDL.Func([IDL.Text, StaffId], [IDL.Opt(Staff)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAvailability' : IDL.Func([IDL.Text, StaffId, Availability], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ClientId = IDL.Text;
  const Client = IDL.Record({
    'id' : ClientId,
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const ServiceId = IDL.Text;
  const Price = IDL.Record({ 'currency' : IDL.Text, 'amount' : IDL.Nat });
  const Service = IDL.Record({
    'id' : ServiceId,
    'name' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'price' : IDL.Opt(Price),
  });
  const StaffId = IDL.Text;
  const Staff = IDL.Record({ 'id' : StaffId, 'name' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PublicBookingRequest = IDL.Record({
    'startTime' : IDL.Int,
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'serviceId' : ServiceId,
    'phone' : IDL.Opt(IDL.Text),
  });
  const AppointmentId = IDL.Text;
  const AppointmentStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'noShow' : IDL.Null,
    'canceled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : AppointmentId,
    'startTime' : IDL.Int,
    'status' : AppointmentStatus,
    'clientId' : ClientId,
    'staffId' : IDL.Opt(StaffId),
    'endTime' : IDL.Int,
    'serviceId' : ServiceId,
  });
  const Availability = IDL.Record({
    'startTime' : IDL.Nat,
    'endTime' : IDL.Nat,
    'dayOfWeek' : IDL.Nat,
  });
  const BusinessProfile = IDL.Record({
    'name' : IDL.Text,
    'timeZone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClient' : IDL.Func([IDL.Text, Client], [], []),
    'addService' : IDL.Func([IDL.Text, Service], [], []),
    'addStaff' : IDL.Func([IDL.Text, Staff], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookPublic' : IDL.Func(
        [IDL.Text, PublicBookingRequest],
        [AppointmentId],
        [],
      ),
    'createAppointment' : IDL.Func([IDL.Text, Appointment], [], []),
    'createBusiness' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllAppointments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getAllClients' : IDL.Func([IDL.Text], [IDL.Vec(Client)], ['query']),
    'getAllServices' : IDL.Func([IDL.Text], [IDL.Vec(Service)], ['query']),
    'getAllStaff' : IDL.Func([IDL.Text], [IDL.Vec(Staff)], ['query']),
    'getAppointment' : IDL.Func(
        [IDL.Text, AppointmentId],
        [IDL.Opt(Appointment)],
        ['query'],
      ),
    'getAvailability' : IDL.Func(
        [IDL.Text, StaffId],
        [IDL.Opt(Availability)],
        ['query'],
      ),
    'getAvailableSlots' : IDL.Func(
        [IDL.Text, ServiceId, IDL.Int],
        [IDL.Vec(IDL.Int)],
        ['query'],
      ),
    'getBusiness' : IDL.Func([IDL.Text], [IDL.Opt(BusinessProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClient' : IDL.Func([IDL.Text, ClientId], [IDL.Opt(Client)], ['query']),
    'getService' : IDL.Func(
        [IDL.Text, ServiceId],
        [IDL.Opt(Service)],
        ['query'],
      ),
    'getStaff' : IDL.Func([IDL.Text, StaffId], [IDL.Opt(Staff)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAvailability' : IDL.Func([IDL.Text, StaffId, Availability], [], []),
  });
};

export const init = ({ IDL }) => { return []; };