/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ServiceId = string;
export type StaffId = string;
export interface Availability {
    startTime: bigint;
    endTime: bigint;
    dayOfWeek: bigint;
}
export interface PublicBookingRequest {
    startTime: bigint;
    name: string;
    email?: string;
    serviceId: ServiceId;
    phone?: string;
}
export interface Service {
    id: ServiceId;
    name: string;
    durationMinutes: bigint;
    price?: Price;
}
export type AppointmentId = string;
export interface Price {
    currency: string;
    amount: bigint;
}
export interface Staff {
    id: StaffId;
    name: string;
}
export interface Client {
    id: ClientId;
    name: string;
    email?: string;
    phone?: string;
}
export interface BusinessProfile {
    name: string;
    timeZone: string;
}
export type ClientId = string;
export interface UserProfile {
    name: string;
}
export interface Appointment {
    id: AppointmentId;
    startTime: bigint;
    status: AppointmentStatus;
    clientId: ClientId;
    staffId?: StaffId;
    endTime: bigint;
    serviceId: ServiceId;
}
export enum AppointmentStatus {
    scheduled = "scheduled",
    noShow = "noShow",
    canceled = "canceled",
    completed = "completed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addClient(businessId: string, client: Client): Promise<void>;
    addService(businessId: string, service: Service): Promise<void>;
    addStaff(businessId: string, staff: Staff): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookPublic(businessId: string, request: PublicBookingRequest): Promise<AppointmentId>;
    createAppointment(businessId: string, appointment: Appointment): Promise<void>;
    createBusiness(businessId: string, name: string, timeZone: string): Promise<void>;
    getAllAppointments(businessId: string): Promise<Array<Appointment>>;
    getAllClients(businessId: string): Promise<Array<Client>>;
    getAllServices(businessId: string): Promise<Array<Service>>;
    getAllStaff(businessId: string): Promise<Array<Staff>>;
    getAppointment(businessId: string, appointmentId: AppointmentId): Promise<Appointment | null>;
    getAvailability(businessId: string, staffId: StaffId): Promise<Availability | null>;
    getAvailableSlots(businessId: string, serviceId: ServiceId, date: bigint): Promise<Array<bigint>>;
    getBusiness(businessId: string): Promise<BusinessProfile | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClient(businessId: string, clientId: ClientId): Promise<Client | null>;
    getService(businessId: string, serviceId: ServiceId): Promise<Service | null>;
    getStaff(businessId: string, staffId: StaffId): Promise<Staff | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setAvailability(businessId: string, staffId: StaffId, availability: Availability): Promise<void>;
}
import type { Appointment as _Appointment, AppointmentId as _AppointmentId, AppointmentStatus as _AppointmentStatus, Availability as _Availability, BusinessProfile as _BusinessProfile, Client as _Client, ClientId as _ClientId, Price as _Price, PublicBookingRequest as _PublicBookingRequest, Service as _Service, ServiceId as _ServiceId, Staff as _Staff, StaffId as _StaffId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addClient(arg0: string, arg1: Client): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addClient(arg0, to_candid_Client_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClient(arg0, to_candid_Client_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addService(arg0: string, arg1: Service): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addService(arg0, to_candid_Service_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addService(arg0, to_candid_Service_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addStaff(arg0: string, arg1: Staff): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStaff(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStaff(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookPublic(arg0: string, arg1: PublicBookingRequest): Promise<AppointmentId> {
        if (this.processError) {
            try {
                const result = await this.actor.bookPublic(arg0, to_candid_PublicBookingRequest_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookPublic(arg0, to_candid_PublicBookingRequest_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAppointment(arg0: string, arg1: Appointment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppointment(arg0, to_candid_Appointment_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppointment(arg0, to_candid_Appointment_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBusiness(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBusiness(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBusiness(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllAppointments(arg0: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppointments(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppointments(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllClients(arg0: string): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllServices(arg0: string): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServices(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServices(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStaff(arg0: string): Promise<Array<Staff>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStaff(arg0);
            return result;
        }
    }
    async getAppointment(arg0: string, arg1: AppointmentId): Promise<Appointment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointment(arg0, arg1);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointment(arg0, arg1);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailability(arg0: string, arg1: StaffId): Promise<Availability | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailability(arg0, arg1);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailability(arg0, arg1);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableSlots(arg0: string, arg1: ServiceId, arg2: bigint): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableSlots(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableSlots(arg0, arg1, arg2);
            return result;
        }
    }
    async getBusiness(arg0: string): Promise<BusinessProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusiness(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusiness(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClient(arg0: string, arg1: ClientId): Promise<Client | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0, arg1);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0, arg1);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getService(arg0: string, arg1: ServiceId): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0, arg1);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0, arg1);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStaff(arg0: string, arg1: StaffId): Promise<Staff | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaff(arg0, arg1);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaff(arg0, arg1);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setAvailability(arg0: string, arg1: StaffId, arg2: Availability): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAvailability(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAvailability(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AppointmentStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Client_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Client): Client {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StaffId]): StaffId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Price]): Price | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Appointment]): Appointment | null {
    return value.length === 0 ? null : from_candid_Appointment_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Availability]): Availability | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BusinessProfile]): BusinessProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Client]): Client | null {
    return value.length === 0 ? null : from_candid_Client_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Service]): Service | null {
    return value.length === 0 ? null : from_candid_Service_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Staff]): Staff | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AppointmentId;
    startTime: bigint;
    status: _AppointmentStatus;
    clientId: _ClientId;
    staffId: [] | [_StaffId];
    endTime: bigint;
    serviceId: _ServiceId;
}): {
    id: AppointmentId;
    startTime: bigint;
    status: AppointmentStatus;
    clientId: ClientId;
    staffId?: StaffId;
    endTime: bigint;
    serviceId: ServiceId;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_AppointmentStatus_n16(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        staffId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.staffId)),
        endTime: value.endTime,
        serviceId: value.serviceId
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ClientId;
    name: string;
    email: [] | [string];
    phone: [] | [string];
}): {
    id: ClientId;
    name: string;
    email?: string;
    phone?: string;
} {
    return {
        id: value.id,
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.email)),
        phone: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ServiceId;
    name: string;
    durationMinutes: bigint;
    price: [] | [_Price];
}): {
    id: ServiceId;
    name: string;
    durationMinutes: bigint;
    price?: Price;
} {
    return {
        id: value.id,
        name: value.name,
        durationMinutes: value.durationMinutes,
        price: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.price))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    noShow: null;
} | {
    canceled: null;
} | {
    completed: null;
}): AppointmentStatus {
    return "scheduled" in value ? AppointmentStatus.scheduled : "noShow" in value ? AppointmentStatus.noShow : "canceled" in value ? AppointmentStatus.canceled : "completed" in value ? AppointmentStatus.completed : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Client>): Array<Client> {
    return value.map((x)=>from_candid_Client_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n24(_uploadFile, _downloadFile, x));
}
function to_candid_AppointmentStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): _AppointmentStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Appointment_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Appointment): _Appointment {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Client_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Client): _Client {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PublicBookingRequest_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublicBookingRequest): _PublicBookingRequest {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Service_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Service): _Service {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: AppointmentId;
    startTime: bigint;
    status: AppointmentStatus;
    clientId: ClientId;
    staffId?: StaffId;
    endTime: bigint;
    serviceId: ServiceId;
}): {
    id: _AppointmentId;
    startTime: bigint;
    status: _AppointmentStatus;
    clientId: _ClientId;
    staffId: [] | [_StaffId];
    endTime: bigint;
    serviceId: _ServiceId;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: to_candid_AppointmentStatus_n11(_uploadFile, _downloadFile, value.status),
        clientId: value.clientId,
        staffId: value.staffId ? candid_some(value.staffId) : candid_none(),
        endTime: value.endTime,
        serviceId: value.serviceId
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ClientId;
    name: string;
    email?: string;
    phone?: string;
}): {
    id: _ClientId;
    name: string;
    email: [] | [string];
    phone: [] | [string];
} {
    return {
        id: value.id,
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ServiceId;
    name: string;
    durationMinutes: bigint;
    price?: Price;
}): {
    id: _ServiceId;
    name: string;
    durationMinutes: bigint;
    price: [] | [_Price];
} {
    return {
        id: value.id,
        name: value.name,
        durationMinutes: value.durationMinutes,
        price: value.price ? candid_some(value.price) : candid_none()
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: bigint;
    name: string;
    email?: string;
    serviceId: ServiceId;
    phone?: string;
}): {
    startTime: bigint;
    name: string;
    email: [] | [string];
    serviceId: _ServiceId;
    phone: [] | [string];
} {
    return {
        startTime: value.startTime,
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        serviceId: value.serviceId,
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): {
    scheduled: null;
} | {
    noShow: null;
} | {
    canceled: null;
} | {
    completed: null;
} {
    return value == AppointmentStatus.scheduled ? {
        scheduled: null
    } : value == AppointmentStatus.noShow ? {
        noShow: null
    } : value == AppointmentStatus.canceled ? {
        canceled: null
    } : value == AppointmentStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
